protected/models/Stream.php
<?php

/**
 * Class Stream
 *
 * This is the model class for table "stream".
 *
 * @property string $id
 * @property datetime $time_start
 * @property datetime $time_end
 * @property smallint unsigned $timer
 * @property string $embed_js
 * @property string $livestream_iframe
 * @property string $countdown_message
 * @property string $ready_message
 * @property string $countdown_background
 * @property string $ready_background
 * @property bool $status
 */
class Stream extends BaseRecord {
	/**
	 * @return string the associated database table name
	 */
	public function tableName() {
		return 'stream';
	}
	
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules() {
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return [
			[ 'status', 'numerical', 'integerOnly' => true ],
			[ 'time_start, time_end, countdown_message, ready_message', 'required' ],
			[ 'countdown_background, ready_background, livestream_iframe, embed_js, timer, youtube_embed_code', 'safe' ],
			[
				'time_start',
				'compare',
				'compareAttribute' => 'time_end',
				'operator'         => '<',
				'message'          => 'Start Time must be less than End Time'
			],
			[
				'time_end',
				'compare',
				'compareAttribute' => 'time_start',
				'operator'         => '>',
				'message'          => 'End Time must be greater than Start Time'
			],
		];
	}
	
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels() {
		return [
			'time_start'           => 'Start Time',
			'time_end'             => 'End Time',
			'timer'                => 'Before Stream (minutes)',
			'embed_js'             => 'JW Player Embed js',
			'livestream_iframe'    => 'Iframe For Livestream',
			'countdown_message'    => 'Countdown Message',
			'ready_message'        => 'Ready to start message',
			'countdown_background' => 'Countdown background url',
			'ready_background'     => 'Ready to start background url',
			'youtube_embed_code'   => 'YouTube Embed Code'
		];
	}
	
	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 *
	 * @param string $className active record class name.
	 *
	 * @return Regimen the static model class
	 */
	public static function model( $className = __CLASS__ ) {
		return parent::model( $className );
	}
	
	/**
	 * @return string
	 */
	public function getDisplayTitle() {
		$time_start = date( 'M d Y, H:i', strtotime( $this->time_start ) );
		$time_end   = date( 'M d Y, H:i', strtotime( $this->time_end ) );
		
		return "{$this->classLabel}: {$time_start} - {$time_end}";
	}
	
	/**
	 * @return array|mixed|null
	 */
	public static function getStream() {
		$criteria            = new CDbCriteria();
		$criteria->condition = 'time_end > :now AND deleted IS NULL';
		$criteria->params    = [ ':now' => date( 'Y-m-d H:i:s' ) ];
		$criteria->order     = 'time_end ASC, id DESC';
		$criteria->limit     = 1;
		
		return static::model()->find( $criteria );
	}
	
	public function getIsReadyMessageVisible() {
		return $this->status
		       && ( strtotime( 'now' ) < strtotime( $this->time_end ) )
		       && ( strtotime( $this->time_start ) >= strtotime( 'now' ) );
	}
	
	public function getIsCountdownMessageVisible() {
		return $this->status
		       && ( strtotime( 'now' ) < strtotime( $this->time_end ) )
		       && ( strtotime( 'now' ) < strtotime( $this->time_start ) );
	}
	
	public function getIsMessageVisible() {
		return $this->isReadyMessageVisible && $this->isCountdownMessageVisible;
	}
	
	public function getIsVideoVisible() {
		return $this->status && ( strtotime( 'now' ) < strtotime( $this->time_end ) );
	}
	
	public function getIsPlayerVisible() {
		return $this->isMessageVisible || $this->isVideoVisible;
	}
}

protected/backend/controllers/VideoController.php
<?php

class VideoController extends BaseController
{
	public function actionIndex()
	{
		$this->menu = [
			['label' => '<span class="fa fa-refresh"></span> Retrieve JW Player Videos', 'url' => $this->createUrl('retrieve')],
		];
		parent::actionIndex();
	}

	public function actionView($id)
	{
		// $menu = array('label'=>'<span class="fa fa-refresh"></span>', 'url'=>$this->createUrl('retrieve'));
		$menu = ['label' => '<span class="fa fa-shopping-cart"></span>', 'url' => ['products', 'id' => $id] + $this->urlParams, 'linkOptions' => ['data-toggle' => 'tooltip', 'title' => 'Related Products'], 'active' => $this->action->id == 'products'];
		array_unshift($this->menu, $menu);

		parent::actionView($id);
	}

	public function actionRetrieve()
	{
		$result = Video::retrieveAll();

		Flash::setFlash('info', $result['saved'] . '/' . $result['count'] . ' videos have been retrieved and updated');

		$this->redirect($this->createUrl('index'));
	}

	/**
	 * Creates a new video.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new $this->class;

		if ($model->columnExists('status'))
			$model->status = 1;

		// check if there are any query params set for default values
		foreach ($model->attributes as $column => $defaultValue) {
			if ($value = Yii::app()->request->getParam($column))
				$model->$column = $value;
		}

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST[$this->class])) {
			$model->attributes = $_POST[$this->class];
			$model->body_part = !empty($_POST[$this->class]['body_part']) ?
				implode(',', $_POST[$this->class]['body_part']) : null;
			$model->equipment = !empty($_POST[$this->class]['equipment']) ?
				implode(',', $_POST[$this->class]['equipment']) : null;

			if ($model->save())
				$this->redirect(['view', $this->primaryKeyName => $model->primaryKey]);
		}

		$this->render('create', [
			'model' => $model,
		]);
	}

	/**
	 * Updates a particular Video model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST[$this->class])) {
			$model->attributes = $_POST[$this->class];
			$model->body_part = !empty($_POST[$this->class]['body_part']) ?
				implode(',', $_POST[$this->class]['body_part']) : null;
			$model->equipment = !empty($_POST[$this->class]['equipment']) ?
				implode(',', $_POST[$this->class]['equipment']) : null;

			if ($model->save())
				$this->redirect(['view', $this->primaryKeyName => $model->primaryKey]);
		}

		$this->render('update', [
			'model' => $model,
		]);
	}

	public function actionProducts($id)
	{
		$model = $this->loadModel($id);

		if (isset($_POST['Video']['product_ids'])) {
			$existing = [];
			$selected = is_array($_POST['Video']['product_ids']) ? $_POST['Video']['product_ids'] : [];
			$added = [];
			$removed = [];
			
			if (count($selected) > 3) {
				Flash::setFlash('error', 'Unable to attach more than 3 products');
				$this->redirect(['video/products', 'id' => $model->id]);
			}
			
			foreach ($model->products as $product)
				$existing[] = $product->id;

			$added = array_diff($selected, $existing);
			$removed = array_diff($existing, $selected);
			
			foreach ($added as $product_id)
				VideoProduct::add($model->id, $product_id);

			foreach ($removed as $product_id)
				VideoProduct::remove($model->id, $product_id);
			
			
			Flash::setFlash('success', 'Related products have been updated');
			$this->redirect(['view', 'id' => $model->id]);
		}

		$model->product_ids = [];
		foreach ($model->products as $product)
			$model->product_ids[] = $product->id;

		$this->render('products', [
			'model' => $model,
		]);
	}
}

protected/controllers/VideoController.php
<?php

class VideoController extends ApiController
{
	public function actionIndex()
	{
		$model = new Video('search');
		$model->attributes = $_GET;
		$scope = isset($_GET['sort']) ? ($_GET['sort'] == 'longest') ? 'byLongest' : 'byShortest' : null;
		$model->isPublic(false)->isLiveClass(false);

		if (!$scope) {
			if (isset($_SERVER['HTTP_REFERER']) && stristr($_SERVER['HTTP_REFERER'], 'mashup-maker'))
				$scope = 'byShortest';
			else
				$scope = 'byLongest';
		}

		$this->renderData([
			'dataProvider' => $model->$scope()->search(9),
			'columns'      => Video::getApiColumns(),
		]);
	}

	public function actionView($id)
	{
		$model = Video::model()->findByPk($id);

		$this->renderData([
			'data'    => $model,
			'columns' => Video::getApiColumns(),
		]);
	}

	public function actionPlayed($id)
	{
		if (Yii::app()->user->isGuest)
			throw new CHttpException('404', 'Page not found.');

		$saved = false;
		$model = new VideoPlayLog;
		$model->video_id = $id;

		if ($model->video) {
			$model->user_id = Yii::app()->user->id;
			$model->status = 1;
			$saved = $model->save();
		}

		$this->renderData([
			'success' => $saved ? 'true' : 'false',
		]);
	}

	public function actionFavorites()
	{
		$model = new Video('search');
		$model->attributes = $_GET;
		$model->favorites();

		$this->renderData([
			'dataProvider' => $model->search(false),
			'columns'      => Video::getApiColumns(),
		]);
	}

	public function actionFavorite($id)
	{
		$success = UserVideo::add(Yii::app()->user->id, $id);
		$this->renderData([
			'success'  => $success ? 'true' : 'false',
			'video_id' => $id,
		]);
	}

	public function actionUnfavorite($id)
	{
		$success = UserVideo::remove(Yii::app()->user->id, $id);
		$this->renderData([
			'success'  => $success ? 'true' : 'false',
			'video_id' => $id,
		]);
	}

	public function actionAllByDuration($duration)
	{
		if (!in_array($duration, Video::getDurations())) {
			throw new CHttpException('404', 'Page not found.');
		}

		$this->renderData([
			'models'  => Video::getByDuration($duration),
			'columns' => Video::getApiColumns(),
		]);
	}

	public function actionAllLiveClasses()
	{
		$this->renderData([
			'models'  => Video::getLiveClasses(),
			'columns' => Video::getApiColumns(),
		]);
	}

	public function actionFilter($duration = null, $is_live_class = null)
	{
		if (!Yii::app()->request->isPostRequest) {
			throw new CHttpException('404', 'Page not found.');
		}

		if ($duration && !in_array($duration, Video::getDurations())) {
			throw new CHttpException('404', 'Page not found.');
		}

		$model = new Video('search');
		$model->attributes = array_filter($_POST);
		$model->is_public = 0;

		if ($duration) {
			$model->duration = $duration;
		} else {
			//TODO: refactor the code, remove else and duration check - make it based on the route
			$is_live_class = 1;
		}

		$model->isPublic(false)->isLiveClass($is_live_class);

		//TODO: find out why $is_public and $is_live_class fields are being set to null on "search" action
		$model->is_live_class = $is_live_class;

		$this->renderData([
			'dataProvider' => $model->search(),
			'columns'      => Video::getApiColumns(),
		]);
	}
}

protected/backend/views/video/_form.php
<div class="form-group">
	<?php echo $form->label($model, 'jwplayer_video_id'); ?>
    <div class="controls">
		<?php echo $form->textField($model, 'jwplayer_video_id'); ?>
		<?php echo $form->error($model, 'jwplayer_video_id'); ?>
    </div>
</div>

<div class="form-group">
	<?php echo $form->label($model, 'instructor_id'); ?>
    <div class="controls">
		<?php echo $form->dropDownList($model, 'instructor_id', ['' => ''] + Users::getInstructors()); ?>
		<?php echo $form->error($model, 'instructor_id'); ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-4">
        <div class="form-group">
			<?php echo $form->label($model, 'strength'); ?>
            <div class="controls">
				<?php echo $form->dropDownList($model, 'strength', ['' => ''] + Video::getLevels()); ?>
				<?php echo $form->error($model, 'strength'); ?>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
			<?php echo $form->label($model, 'cardio'); ?>
            <div class="controls">
				<?php echo $form->dropDownList($model, 'cardio', ['' => ''] + Video::getLevels()); ?>
				<?php echo $form->error($model, 'cardio'); ?>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
			<?php echo $form->label($model, 'restorative'); ?>
            <div class="controls">
				<?php echo $form->dropDownList($model, 'restorative', ['' => ''] + Video::getLevels()); ?>
				<?php echo $form->error($model, 'restorative'); ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
			<?php echo $form->label($model, 'body_part'); ?>
            <div class="controls">
				<?php echo $form->dropDownList($model, 'body_part', Video::getBodyParts(), [
					'multiple' => 'multiple',
					'options'  => !empty($model->body_part) ?
						array_fill_keys(explode(',', $model->body_part), ['selected' => 'selected']) :
						null,
				]); ?>
				<?php echo $form->error($model, 'body_part'); ?>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="form-group">
			<?php echo $form->label($model, 'equipment'); ?>
            <div class="controls">
				<?php echo $form->dropDownList($model, 'equipment', Video::getEquipment(), [
					'multiple' => 'multiple',
					'options'  => !empty($model->equipment) ?
						array_fill_keys(explode(',', $model->equipment), ['selected' => 'selected']) :
						null,
				]); ?>
				<?php echo $form->error($model, 'equipment'); ?>
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="controls">
		<?php echo $form->checkBox($model, 'is_live_class'); ?>
		<?php echo $form->label($model, 'is_live_class'); ?>
		<?php echo $form->error($model, 'is_live_class'); ?>
    </div>
</div>
<div class="form-group">
    <div class="controls">
		<?php echo $form->checkBox($model, 'is_new'); ?>
		<?php echo $form->label($model, 'is_new'); ?>
		<?php echo $form->error($model, 'is_new'); ?>
    </div>
</div>

<div class="form-group">
    <div class="controls">
		<?php echo $form->label($model, 'is_public', ['label' => 'Video Restrictions']); ?>
        <div class="inline">
			<?php echo $form->radioButtonList($model, 'is_public', ['0' => 'Member Only', '1' => 'Preview']); ?>
        </div>
		<?php echo $form->error($model, 'is_public'); ?>
    </div>
</div>

<div class="form-group">
	<?php echo $form->labelEx($model, 'weight'); ?>
    <div class="controls">
		<?php echo $form->dropDownList($model, 'weight', CString::range(-20, 20)); ?>
        <div class="note">Set the weight to change the order of preview videos. Lower weight = ranked higher</div>
		<?php echo $form->error($model, 'weight'); ?>
    </div>
</div>

protected/backend/views/video/_search.php
<div class="form">

<?php $form=$this->beginWidget('ActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="form-content">
		<?php if ($model->columnExists('title')): ?>
		<div class="form-group">
			<?php echo $form->label($model,'title'); ?>
			<div class="controls">
				<?php echo $form->textField($model,'title',array('class'=>'form-control','maxlength'=>11)); ?>
			</div>
		</div>
		<?php endif; ?>

		<div class="form-group">
			<div class="controls">
				<div class="row">
					<div class="col-xs-6">
						<?php echo $form->labelEx($model, 'type'); ?>
						<?php echo $form->dropDownList($model,'type',array(''=>'')+Video::getTypes()); ?>
					</div>
					<div class="col-xs-6">
						<?php echo $form->labelEx($model, 'level'); ?>
						<?php echo $form->dropDownList($model,'level',array(''=>'')+Video::getLevels()); ?>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group">
			<?php echo $form->labelEx($model, 'is_public'); ?>
			<div class="controls">
				<?php echo $form->dropDownList($model,'is_public',array(''=>'', '1'=>'Yes (Preview)', '0'=>'No (Member Only)')); ?>
			</div>
		</div>

		<div class="form-group">
			<?php echo $form->labelEx($model, 'instructor_id'); ?>
			<div class="controls">
				<?php echo $form->dropDownList($model,'instructor_id',array(''=>'')+Users::getInstructors()); ?>
			</div>
		</div>

		<div class="form-group">
			<?php echo $form->label($model,'status'); ?>
			<div class="controls">
				<?php echo $form->dropDownList($model,'status',array(''=>'All','1'=>'Published','0'=>'Unpublished')); ?>
			</div>
		</div>

		<div class="form-group">
			<?php echo $form->labelEx($model, 'created'); ?>
			<div class="controls">
				<div class="row">
					<div class="col-xs-6">
						<?php echo $form->dateField($model,'created_from',array('class'=>'form-control input-sm','placeholder'=>$model->getAttributeLabel('created_from'))); ?>
					</div>
					<div class="col-xs-6">
						<?php echo $form->dateField($model,'created_to',array('class'=>'form-control input-sm','placeholder'=>$model->getAttributeLabel('created_to'))); ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="form-actions buttons">
		<?php echo Html::button('Clear', array('class'=>'btn btn-sm btn-default', 'data-toggle'=>'clearForm')); ?>
		<?php echo Html::submitButton('Search', array('class'=>'btn btn-sm btn-primary pull-right')); ?>
		<div class="clearfix"></div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/backend/views/video/products.php
<div class="page-header">
	<h1><?php echo $model->displayTitle; ?></h1>
	<h2><?php echo $model->classLabel; ?></h2>
</div>

<div class="form">
<?php 
	$form=$this->beginWidget('ActiveForm', array(
		'id'=>'post-form',
		'enableAjaxValidation'=>false,
		'htmlOptions'=>array('enctype' => 'multipart/form-data'),
	)); 
?>

	<div class="form-group">
		<?php echo $form->label($model, 'product_ids', array('label'=>'Related Products')); ?>
		<div class="controls">
			<?php echo $form->checkboxList($model, 'product_ids', Product::getList()); ?>
			<?php echo $form->error($model,'product_ids'); ?>
		</div>
	</div>

	<div class="form-actions buttons">
		<?php echo Html::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->